// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD518cl5X3-H7n-qyb2yfFTlB3ytigTsew',
    appId: '1:466431904054:web:d877b44f16939484448b97',
    messagingSenderId: '466431904054',
    projectId: 'chatpulse-c4de3',
    authDomain: 'chatpulse-c4de3.firebaseapp.com',
    storageBucket: 'chatpulse-c4de3.appspot.com',
    measurementId: 'G-H2XCQVSJX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClyr_FDs6u4CrsS95ZGoM0Eiy2lPUmVkM',
    appId: '1:466431904054:android:8ae299acb3a1e76e448b97',
    messagingSenderId: '466431904054',
    projectId: 'chatpulse-c4de3',
    storageBucket: 'chatpulse-c4de3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx-WWRoVqe0vISeOF_ezh_BD-DJ79jk2c',
    appId: '1:466431904054:ios:ec5cd8d86421b6ad448b97',
    messagingSenderId: '466431904054',
    projectId: 'chatpulse-c4de3',
    storageBucket: 'chatpulse-c4de3.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
