// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUx7Km-0ZWw1k3sPaP8LsXVCB-Y09d148',
    appId: '1:975667499823:web:236905bb2db2e9be0a87da',
    messagingSenderId: '975667499823',
    projectId: 'furniwas-914d6',
    authDomain: 'furniwas-914d6.firebaseapp.com',
    storageBucket: 'furniwas-914d6.appspot.com',
    measurementId: 'G-HVRLKBN962',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeufCIHwdTZnrfK0C_Ux0LPSgVwCvDCPI',
    appId: '1:975667499823:android:a156a173be1880e90a87da',
    messagingSenderId: '975667499823',
    projectId: 'furniwas-914d6',
    storageBucket: 'furniwas-914d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiTG2TU-sEE2ZokjE7en5hwEFmg3cLX-Y',
    appId: '1:975667499823:ios:7eb353021e6a852b0a87da',
    messagingSenderId: '975667499823',
    projectId: 'furniwas-914d6',
    storageBucket: 'furniwas-914d6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiTG2TU-sEE2ZokjE7en5hwEFmg3cLX-Y',
    appId: '1:975667499823:ios:7eb353021e6a852b0a87da',
    messagingSenderId: '975667499823',
    projectId: 'furniwas-914d6',
    storageBucket: 'furniwas-914d6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUx7Km-0ZWw1k3sPaP8LsXVCB-Y09d148',
    appId: '1:975667499823:web:54ab7a620536cf9b0a87da',
    messagingSenderId: '975667499823',
    projectId: 'furniwas-914d6',
    authDomain: 'furniwas-914d6.firebaseapp.com',
    storageBucket: 'furniwas-914d6.appspot.com',
    measurementId: 'G-83X35JLJWK',
  );

}